version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/garage_ssh_gate/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "russh"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "russh-keys"
        update-types:
          - "version-update:semver-major"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
